#!/usr/bin/env python3
"""Refresh the version dropdown in .github/ISSUE_TEMPLATE/bug_report.yml from GitHub releases."""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

BUG_REPORT_PATH = Path(".github/ISSUE_TEMPLATE/bug_report.yml")
START_SENTINEL = "        # <!-- AUTOGENERATED_VERSION_OPTIONS_START -->"
END_SENTINEL = "        # <!-- AUTOGENERATED_VERSION_OPTIONS_END -->"


def get_releases() -> list[str]:
    """Fetch releases using gh CLI, filtering to stable and beta releases."""
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    cmd = ["gh", "release", "list", "--limit", "100", "--json", "tagName"]
    env = os.environ.copy()
    if token:
        env["GH_TOKEN"] = token
    result = subprocess.run(cmd, capture_output=True, text=True, check=True, env=env)
    data = json.loads(result.stdout)
    tags: list[str] = []
    # Match stable (vX.Y.Z) or beta (vX.Y.Z-beta.N) releases, excluding legacy -dev.* tags
    tag_pattern = re.compile(r"^v\d+\.\d+\.\d+(?:-beta\.\d+)?$")
    for item in data:
        tag = item.get("tagName")
        if tag and tag_pattern.match(tag) and tag not in tags:
            tags.append(tag)
            if len(tags) >= 15:
                break
    return tags


def main() -> None:
    if not BUG_REPORT_PATH.exists():
        print(f"Error: {BUG_REPORT_PATH} not found", file=sys.stderr)
        sys.exit(1)

    try:
        tags = get_releases()
    except Exception as err:
        print(f"Failed to fetch releases: {err}", file=sys.stderr)
        sys.exit(1)

    if not tags:
        print("No releases found, skipping update.")
        return

    options = [*tags, "Other / Older"]

    content = BUG_REPORT_PATH.read_text(encoding="utf-8")
    if START_SENTINEL not in content or END_SENTINEL not in content:
        print("Sentinels not found in bug_report.yml", file=sys.stderr)
        sys.exit(1)

    options_block = "\n".join(f"        - {option}" for option in options)
    replacement = f"{START_SENTINEL}\n{options_block}\n{END_SENTINEL}"

    pattern = re.compile(re.escape(START_SENTINEL) + r".*?" + re.escape(END_SENTINEL), re.DOTALL)
    new_content = pattern.sub(replacement, content)

    if new_content != content:
        BUG_REPORT_PATH.write_text(new_content, encoding="utf-8")
        print("Updated bug_report.yml version options.")
    else:
        print("No changes to bug_report.yml version options.")


if __name__ == "__main__":
    main()
